name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.8

      - name: Unit Testing With Python
        uses: PrajjawalBanati/Python-actions@0.0.1

      - name: Python flake8 Lint
        uses: py-actions/flake8@v2.3.0
                  